### ISSUE TITLE
'Dart SDK' page issue

### ISSUE THREAD

**Issue by ngonen** [dart-lang/site-shared#62]
Page URL: https://www.dartlang.org/tools/sdk/
Page source: https://github.com/dart-lang/site-shared/tree/master/src/tools/sdk/index.md

referral to <a href="http://brew.sh">install homebrew</a> was incomplete b/c it breaks for many on installing xcode-select --install (for command line tools) - this is broken via the xcode installer. Instead I followed thread to direct location of the command tools at <a href="https://developer.apple.com/download/more/?name=for%20Xcode">apple developer</a> so I think you should add a comment b/c that would save others half hour fo running around. just my 2 cents.

**Comment by kwalrath** [comment]
Thanks very much for the feedback. Just to make sure I understand, did the https://brew.sh/ instructions not work for you because you hadn't installed Xcode command-line tools yet?

It seems like brew should fix _their_ instructions, but since that's out of our control, I'm willing to provide extra guidance.

**Comment by kwalrath** [comment]
@ngonen or anyone else, can you help me understand this better?

**Comment by chalin** [comment]
SDK pages have moved to site-www. If this is still an issue, please [open an issue over there](https://github.com/dart-lang/site-www/issues/new).
